### ISSUE TITLE
Players sometimes connect, but fail to be provisioned a player ID

### ISSUE THREAD

**Issue by terrehbyte** [terrehbyte/TankBattle#3]
## Expected Behavior

Players should connect and get a player ID or be rejected from the server.
## Current Behavior

Players may connect and establish a connection, but be left in limbo, failing to verify that they have been provisioned a player ID despite the server generating a tank.

**Comment by terrehbyte** [comment]
Is something blocking execution of the callbacks? If a player fails the provisioning but remains connected, connecting a second player seems to "dislodge" the first, causing both to start receiving state updates.

Connecting a third player gets them stuck into a loop, waiting for the provisioning process again. Wait. Seems like they get processed eventually?

**Comment by Silvainius01** [comment]
In your vanilla project, launching the client will still not connect to the server, even after a restart of unity.

**Comment by terrehbyte** [comment]
What branch of the project were you looking at?
